### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by callodacity** [hexojs/hexo-deployer-openshift#5]
As the title says. Is there a way to make the server redirect to `public/404.html` instead of the default superstatic 404 page?

**Comment by NoahDragon** [comment]
I think put 404.html under the root folder would work.

**Comment by callodacity** [comment]
No it didn't. It seems superstatic was rather outdated. 

I forked the repo and updated it to look for a 404.html here https://github.com/callodacity/hexo-deployer-openshift2
